# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: 'azureagentpool'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Azure subscription 1(38668a37-4cf7-4cec-9cc3-8e66318abef1)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az group create --name myresourcegrp --location eastus' 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(38668a37-4cf7-4cec-9cc3-8e66318abef1)'
    subscriptionId: '38668a37-4cf7-4cec-9cc3-8e66318abef1'
    action: 'DeleteRG'
    resourceGroupName: 'myresourcegrp'